### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by iChintanSoni** [deakjahn/sqflite_web#15]
When I try to install sqflite_web, I get this error:

```
[myapp] flutter pub get
Running "flutter pub get" in myapp...                          967ms
exit code 0

--

[myapp] flutter pub get
Running "flutter pub get" in myapp...                       
Because every version of sqflite_web from git depends on sqflite_common ^1.0.3 and sqflite_common_ffi 2.0.0+1 depends on sqflite_common >=2.0.0 <4.0.0, sqflite_web from git is incompatible with sqflite_common_ffi 2.0.0+1.
And because no versions of sqflite_common_ffi match >2.0.0+1 <3.0.0, sqflite_web from git is incompatible with sqflite_common_ffi ^2.0.0+1.
So, because myapp depends on both sqflite_common_ffi ^2.0.0+1 and sqflite_web from git, version solving failed.
pub get failed (1; So, because myapp depends on both sqflite_common_ffi ^2.0.0+1 and sqflite_web from git, version solving failed.)
exit code 1
```

Has anyone faced this issue? 
Any pointers would be appreciated. Thanks.

**Comment by QuentinCG** [comment]
Can you provide your full pubspec.yaml ?
(or at least this content:
```yaml
environment:
  sdk: ???

dependencies:
 ???

dev_dependencies:
 ???
```
)



Here is what should work (or at least did work) :

```
dependencies:
  # Database handling (if you want to support other platforms than web too)
  sqflite: ^1.3.2+2

dev_dependencies:
  # For sqflite web compatibility (will save the database IN MEMORY => not stored)
  sqflite_web:
    git:
      url: https://github.com/deakjahn/sqflite_web.git
      ref: master
````

@deakjahn The readme is pointing to my repo... My mistake from the pull request I did few months ago
