### ISSUE TITLE
unable to install package

### ISSUE THREAD

**Issue by hoseinmoradi** [deakjahn/sqflite_web#20]
Hi guys
I have got a problem in install packages. can you help me?

`Because url_launcher_platform_interface 1.0.9 depends on plugin_platform_interface ^1.0.1 and no versions of url_launcher_platform_interface match >1.0.9 <2.0.0, url_launcher_platform_interface ^1.0.9 requires plugin_platform_interface ^1.0.1.
And because every version of sqflite_web from git depends on plugin_platform_interface ^2.0.0, sqflite_web from git is incompatible with url_launcher_platform_interface ^1.0.9.
And because url_launcher 5.7.10 depends on url_launcher_platform_interface ^1.0.9 and no versions of url_launcher match >5.7.10 <6.0.0, sqflite_web from git is incompatible with url_launcher ^5.7.10.
So, because app depends on both url_launcher ^5.7.10 and sqflite_web from git, version solving failed.
pub get failed (1; So, because app depends on both url_launcher ^5.7.10 and sqflite_web from git, version solving failed.)
exit code 1`

pubspec.yaml : 

```

name: app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  page_transition: ^1.1.4
  argon_buttons_flutter: ^1.0.6
  pin_code_fields: ^7.0.0
  introduction_screen: ^1.0.9
  retrofit: ^1.3.4+1
  loading: ^1.0.2
  dio: ^3.0.10
  json_serializable: ^3.5.1
  json_annotation: any
  equatable: ^1.2.5
  bloc: ^6.1.1
  flutter_launcher_icons: ^0.7.3
  flutter_bloc: ^6.1.1
  shared_preferences: any
  persistent_bottom_nav_bar: any
  carousel_slider: ^3.0.0
  tree_view: ^0.0.5
  video_player: any
  # connectivity_plus: ^0.8.1
  top_snackbar_flutter: ^1.0.0
  shamsi_date: ^0.15.0
  sqflite: ^1.3.2+2
  icon_badge: ^0.0.1+5
  path_provider: any
  # permission_handler: ^4.4.0+hotfix.2
  webview_flutter: ^2.0.10
  intl: ^0.16.1
  image_pickers: ^1.1.0
  page_slider: ^0.0.2
  # firebase_messaging: ^7.0.3
  # firebase_core: any
  timeline_tile: ^2.0.0
  audioplayerui: ^0.0.7
  flutter_html: ^0.8.2
  url_launcher: ^5.7.10
  chewie: any
  pdf_viewer_jk: any
  uuid: ^2.2.2
  
dev_dependencies:
  sqflite_web:
    git:
      url: https://github.com/deakjahn/sqflite_web.git
      ref: master
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any


flutter_icons:
  image_path_android: "images/logoo.png"
  image_path_ios: "images/logoo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  fonts:
     - family: dana
       fonts:
          - asset: assets/dana.ttf 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
